// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POPSAPI.Model;

namespace POPSAPI.Migrations
{
    [DbContext(typeof(POPSContext))]
    partial class POPSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("POPSAPI.Model.Item", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasColumnName("ITCODE")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnName("ITDESC")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<decimal>("ItemRate")
                        .HasColumnName("ITRATE")
                        .HasColumnType("Money");

                    b.HasKey("ItemCode")
                        .HasName("Itm_Primary_key");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("POPSAPI.Model.PoDetail", b =>
                {
                    b.Property<string>("PuchaseOrderNumber")
                        .HasColumnName("PONO")
                        .HasColumnType("Char(4)");

                    b.Property<string>("ItemNumber")
                        .HasColumnName("ITCODE")
                        .HasColumnType("CHAR(4)");

                    b.Property<int>("Quantity")
                        .HasColumnName("QTY")
                        .HasColumnType("integer");

                    b.HasKey("PuchaseOrderNumber", "ItemNumber")
                        .HasName("pod_primary_key");

                    b.HasIndex("ItemNumber");

                    b.ToTable("PoDetails");
                });

            modelBuilder.Entity("POPSAPI.Model.PoMaster", b =>
                {
                    b.Property<string>("PoNumber")
                        .HasColumnName("PONO")
                        .HasColumnType("CHAR(4)");

                    b.Property<DateTime>("PoDate")
                        .HasColumnName("PODATE")
                        .HasColumnType("timestamp");

                    b.Property<string>("SUPLNO")
                        .IsRequired()
                        .HasColumnName("SUPLNO")
                        .HasColumnType("CHAR(4)");

                    b.HasKey("PoNumber")
                        .HasName("pom_primary_key");

                    b.HasIndex("SUPLNO");

                    b.ToTable("PoMasters");
                });

            modelBuilder.Entity("POPSAPI.Model.Supplier", b =>
                {
                    b.Property<string>("SupplierNumber")
                        .HasColumnName("SUPLNO")
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("SupplierAddress")
                        .HasColumnName("SUPLADDR")
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnName("SUPLNAME")
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("SupplierNumber")
                        .HasName("suppl_primary_key");

                    b.ToTable("SUPPLIER");
                });

            modelBuilder.Entity("POPSAPI.Model.PoDetail", b =>
                {
                    b.HasOne("POPSAPI.Model.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POPSAPI.Model.PoMaster", "PurchaseOrderMaster")
                        .WithMany("Details")
                        .HasForeignKey("PuchaseOrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("POPSAPI.Model.PoMaster", b =>
                {
                    b.HasOne("POPSAPI.Model.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SUPLNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
